// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.14.0
// source: pces.proto

package pces

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Certificate status information.
type CertificateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ValidAfter    int64                  `protobuf:"varint,3,opt,name=valid_after,json=validAfter,proto3" json:"valid_after,omitempty"`
	ValidBefore   int64                  `protobuf:"varint,4,opt,name=valid_before,json=validBefore,proto3" json:"valid_before,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateStatus) Reset() {
	*x = CertificateStatus{}
	mi := &file_pces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateStatus) ProtoMessage() {}

func (x *CertificateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateStatus.ProtoReflect.Descriptor instead.
func (*CertificateStatus) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateStatus) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CertificateStatus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CertificateStatus) GetValidAfter() int64 {
	if x != nil {
		return x.ValidAfter
	}
	return 0
}

func (x *CertificateStatus) GetValidBefore() int64 {
	if x != nil {
		return x.ValidBefore
	}
	return 0
}

func (x *CertificateStatus) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// Agent status information.
type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uptime        int64                  `protobuf:"varint,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Certificates  []*CertificateStatus   `protobuf:"bytes,2,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_pces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{1}
}

func (x *AgentStatus) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *AgentStatus) GetCertificates() []*CertificateStatus {
	if x != nil {
		return x.Certificates
	}
	return nil
}

// Request to renew certificates.
type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_pces_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{2}
}

func (x *RenewRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RenewRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_pces_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{3}
}

// Request to get agent status.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pces_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *AgentStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pces_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Request to get certificate data.
type GetTLSCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTLSCertRequest) Reset() {
	*x = GetTLSCertRequest{}
	mi := &file_pces_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTLSCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTLSCertRequest) ProtoMessage() {}

func (x *GetTLSCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTLSCertRequest.ProtoReflect.Descriptor instead.
func (*GetTLSCertRequest) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{6}
}

func (x *GetTLSCertRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GetTLSCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertData      []byte                 `protobuf:"bytes,1,opt,name=cert_data,json=certData,proto3" json:"cert_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTLSCertResponse) Reset() {
	*x = GetTLSCertResponse{}
	mi := &file_pces_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTLSCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTLSCertResponse) ProtoMessage() {}

func (x *GetTLSCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTLSCertResponse.ProtoReflect.Descriptor instead.
func (*GetTLSCertResponse) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{7}
}

func (x *GetTLSCertResponse) GetCertData() []byte {
	if x != nil {
		return x.CertData
	}
	return nil
}

// Request to sign data.
type SignWithTLSCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignWithTLSCertRequest) Reset() {
	*x = SignWithTLSCertRequest{}
	mi := &file_pces_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignWithTLSCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignWithTLSCertRequest) ProtoMessage() {}

func (x *SignWithTLSCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignWithTLSCertRequest.ProtoReflect.Descriptor instead.
func (*SignWithTLSCertRequest) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{8}
}

func (x *SignWithTLSCertRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SignWithTLSCertRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SignWithTLSCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignWithTLSCertResponse) Reset() {
	*x = SignWithTLSCertResponse{}
	mi := &file_pces_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignWithTLSCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignWithTLSCertResponse) ProtoMessage() {}

func (x *SignWithTLSCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pces_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignWithTLSCertResponse.ProtoReflect.Descriptor instead.
func (*SignWithTLSCertResponse) Descriptor() ([]byte, []int) {
	return file_pces_proto_rawDescGZIP(), []int{9}
}

func (x *SignWithTLSCertResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_pces_proto protoreflect.FileDescriptor

const file_pces_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pces.proto\x12\x04pces\"\xbd\x01\n" +
	"\x11CertificateStatus\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vvalid_after\x18\x03 \x01(\x03R\n" +
	"validAfter\x12!\n" +
	"\fvalid_before\x18\x04 \x01(\x03R\vvalidBefore\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"b\n" +
	"\vAgentStatus\x12\x16\n" +
	"\x06uptime\x18\x01 \x01(\x03R\x06uptime\x12;\n" +
	"\fcertificates\x18\x02 \x03(\v2\x17.pces.CertificateStatusR\fcertificates\"<\n" +
	"\fRenewRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x0f\n" +
	"\rRenewResponse\"\x0f\n" +
	"\rStatusRequest\";\n" +
	"\x0eStatusResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\v2\x11.pces.AgentStatusR\x06status\")\n" +
	"\x11GetTLSCertRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"1\n" +
	"\x12GetTLSCertResponse\x12\x1b\n" +
	"\tcert_data\x18\x01 \x01(\fR\bcertData\"B\n" +
	"\x16SignWithTLSCertRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"7\n" +
	"\x17SignWithTLSCertResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature2\x83\x02\n" +
	"\tPCeSAgent\x120\n" +
	"\x05Renew\x12\x12.pces.RenewRequest\x1a\x13.pces.RenewResponse\x123\n" +
	"\x06Status\x12\x13.pces.StatusRequest\x1a\x14.pces.StatusResponse\x12?\n" +
	"\n" +
	"GetTLSCert\x12\x17.pces.GetTLSCertRequest\x1a\x18.pces.GetTLSCertResponse\x12N\n" +
	"\x0fSignWithTLSCert\x12\x1c.pces.SignWithTLSCertRequest\x1a\x1d.pces.SignWithTLSCertResponseB,Z*github.com/facebookincubator/pces/api/pcesb\x06proto3"

var (
	file_pces_proto_rawDescOnce sync.Once
	file_pces_proto_rawDescData []byte
)

func file_pces_proto_rawDescGZIP() []byte {
	file_pces_proto_rawDescOnce.Do(func() {
		file_pces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pces_proto_rawDesc), len(file_pces_proto_rawDesc)))
	})
	return file_pces_proto_rawDescData
}

var file_pces_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pces_proto_goTypes = []any{
	(*CertificateStatus)(nil),       // 0: pces.CertificateStatus
	(*AgentStatus)(nil),             // 1: pces.AgentStatus
	(*RenewRequest)(nil),            // 2: pces.RenewRequest
	(*RenewResponse)(nil),           // 3: pces.RenewResponse
	(*StatusRequest)(nil),           // 4: pces.StatusRequest
	(*StatusResponse)(nil),          // 5: pces.StatusResponse
	(*GetTLSCertRequest)(nil),       // 6: pces.GetTLSCertRequest
	(*GetTLSCertResponse)(nil),      // 7: pces.GetTLSCertResponse
	(*SignWithTLSCertRequest)(nil),  // 8: pces.SignWithTLSCertRequest
	(*SignWithTLSCertResponse)(nil), // 9: pces.SignWithTLSCertResponse
}
var file_pces_proto_depIdxs = []int32{
	0, // 0: pces.AgentStatus.certificates:type_name -> pces.CertificateStatus
	1, // 1: pces.StatusResponse.status:type_name -> pces.AgentStatus
	2, // 2: pces.PCeSAgent.Renew:input_type -> pces.RenewRequest
	4, // 3: pces.PCeSAgent.Status:input_type -> pces.StatusRequest
	6, // 4: pces.PCeSAgent.GetTLSCert:input_type -> pces.GetTLSCertRequest
	8, // 5: pces.PCeSAgent.SignWithTLSCert:input_type -> pces.SignWithTLSCertRequest
	3, // 6: pces.PCeSAgent.Renew:output_type -> pces.RenewResponse
	5, // 7: pces.PCeSAgent.Status:output_type -> pces.StatusResponse
	7, // 8: pces.PCeSAgent.GetTLSCert:output_type -> pces.GetTLSCertResponse
	9, // 9: pces.PCeSAgent.SignWithTLSCert:output_type -> pces.SignWithTLSCertResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pces_proto_init() }
func file_pces_proto_init() {
	if File_pces_proto != nil {
		return
	}
	file_pces_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pces_proto_rawDesc), len(file_pces_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pces_proto_goTypes,
		DependencyIndexes: file_pces_proto_depIdxs,
		MessageInfos:      file_pces_proto_msgTypes,
	}.Build()
	File_pces_proto = out.File
	file_pces_proto_goTypes = nil
	file_pces_proto_depIdxs = nil
}
